create table categorias_gasto
(
    id                  bigint generated by default as identity
        constraint categorias_gasto_pkey
            primary key,
    nombre              varchar(100)         not null
        constraint categorias_gasto_nombre_key
            unique,
    descripcion         varchar(255),
    presupuesto_mensual numeric(12, 2),
    activo              boolean default true not null,
    created_at          timestamp            not null,
    updated_at          timestamp
);

alter table categorias_gasto
    owner to postgres;

create index idx_cat_gasto_nombre
    on categorias_gasto (nombre);

