create table gastos
(
    id                 bigint generated by default as identity
        constraint gastos_pkey
            primary key,
    categoria_gasto_id bigint         not null
        constraint fk_gastos_categoria
            references categorias_gasto,
    proveedor_id       bigint
        constraint fk_gastos_proveedor
            references proveedores,
    sucursal_id        bigint
        constraint fk_gastos_sucursal
            references sucursales,
    monto              numeric(12, 2) not null,
    fecha              timestamp      not null,
    metodo_pago_id     bigint
        constraint fk_gastos_metodo_pago
            references metodos_pago,
    referencia         varchar(200),
    nota               text,
    comprobante_url    varchar(500),
    usuario_id         bigint
        constraint fk_gastos_usuario
            references usuarios,
    created_at         timestamp      not null,
    updated_at         timestamp
);

alter table gastos
    owner to postgres;

create index idx_gasto_fecha
    on gastos (fecha);

create index idx_gasto_categoria
    on gastos (categoria_gasto_id);

create index idx_gasto_sucursal
    on gastos (sucursal_id);

