create table ingredientes
(
    id                  bigint generated by default as identity
        constraint ingredientes_pkey
            primary key,
    activo              boolean        not null,
    categoria           varchar(100),
    costo_unitario_base numeric(14, 6) not null,
    nombre              varchar(200)   not null,
    sku                 varchar(50),
    stock_minimo        numeric(12, 3),
    proveedor_id        bigint
        constraint fkgk1gjpmmuki3dcm2dh9j751al
            references proveedores,
    unidad_base_id      bigint         not null
        constraint fkvwss72d9u8uegjtrdij24q57
            references unidades
);

alter table ingredientes
    owner to postgres;

