create table inventario_movimientos
(
    id             bigint generated by default as identity
        constraint inventario_movimientos_pkey
            primary key,
    caducidad      date,
    cantidad       numeric(14, 6) not null,
    costo_total    numeric(14, 6) not null,
    costo_unitario numeric(14, 6) not null,
    fecha          timestamp(6)   not null,
    lote           varchar(100),
    nota           text,
    ref_id         bigint,
    ref_tipo       varchar(50),
    tipo           varchar(20)    not null,
    ingrediente_id bigint         not null
        constraint fk863cv6615cwednqxpvv9nxflc
            references ingredientes,
    unidad_id      bigint         not null
        constraint fkiyvh8grvnrayh7qg163o55k65
            references unidades
);

alter table inventario_movimientos
    owner to postgres;

create index idx_inv_mov_ingrediente_fecha
    on inventario_movimientos (ingrediente_id, fecha);

create index idx_inv_mov_tipo_fecha
    on inventario_movimientos (tipo, fecha);

