create table mermas
(
    id             bigint generated by default as identity
        constraint mermas_pkey
            primary key,
    cantidad       numeric(14, 6) not null,
    costo_total    numeric(14, 6),
    costo_unitario numeric(14, 6),
    fecha          timestamp(6)   not null,
    motivo         text           not null,
    ingrediente_id bigint         not null
        constraint fk9b6npsdue246yyg2n04i1ah7w
            references ingredientes,
    responsable_id bigint
        constraint fk38650a542g9hbyh7do14g0x1x
            references usuarios,
    unidad_id      bigint         not null
        constraint fknj8bvpjp1qfly6ii0lveuptde
            references unidades
);

alter table mermas
    owner to postgres;

