create table permisos
(
    id          bigint generated by default as identity
        constraint permisos_pkey
            primary key,
    created_at  timestamp(6) not null,
    descripcion varchar(255),
    nombre      varchar(100) not null
        constraint ukmd9j2tw7h6dxprrypo0itpnyp
            unique
);

alter table permisos
    owner to postgres;

