create table proveedores
(
    id       bigint generated by default as identity
        constraint proveedores_pkey
            primary key,
    activo   boolean      not null,
    contacto varchar(200),
    email    varchar(100),
    nombre   varchar(200) not null,
    telefono varchar(20)
);

alter table proveedores
    owner to postgres;

