create table unidades
(
    id          bigint generated by default as identity
        constraint unidades_pkey
            primary key,
    abreviatura varchar(10)    not null,
    descripcion text,
    factor_base numeric(12, 6) not null,
    nombre      varchar(100)   not null
);

alter table unidades
    owner to postgres;

