-- ==============================================
-- V3: Crear tablas de gastos y categorías de gastos
-- ==============================================

-- Crear tablas que pueden no existir aún (creadas por Hibernate)
-- Estas tablas se crean aquí para asegurar que existan antes de crear foreign keys

-- Tabla de proveedores (si no existe)
CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    contacto VARCHAR(200),
    telefono VARCHAR(20),
    email VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- Tabla de métodos de pago (si no existe)
CREATE TABLE IF NOT EXISTS metodos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    requiere_referencia BOOLEAN DEFAULT FALSE NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    descripcion TEXT
);

-- Tabla de categorías de gastos
CREATE TABLE IF NOT EXISTS categorias_gasto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    presupuesto_mensual DECIMAL(12, 2),
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

-- Tabla de gastos
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_gasto_id BIGINT NOT NULL,
    proveedor_id BIGINT,
    sucursal_id BIGINT,
    monto DECIMAL(12, 2) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    metodo_pago_id BIGINT,
    referencia VARCHAR(200),
    nota TEXT,
    comprobante_url VARCHAR(500),
    usuario_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_gastos_categoria FOREIGN KEY (categoria_gasto_id) REFERENCES categorias_gasto(id),
    CONSTRAINT fk_gastos_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id),
    CONSTRAINT fk_gastos_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id),
    CONSTRAINT fk_gastos_metodo_pago FOREIGN KEY (metodo_pago_id) REFERENCES metodos_pago(id),
    CONSTRAINT fk_gastos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Índices para optimizar consultas
CREATE INDEX IF NOT EXISTS idx_gasto_fecha ON gastos(fecha);
CREATE INDEX IF NOT EXISTS idx_gasto_categoria ON gastos(categoria_gasto_id);
CREATE INDEX IF NOT EXISTS idx_gasto_sucursal ON gastos(sucursal_id);
CREATE INDEX IF NOT EXISTS idx_cat_gasto_nombre ON categorias_gasto(nombre);

-- Insertar categorías de gastos iniciales
INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Insumos', 'Compra de ingredientes e insumos para producción', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Insumos');

INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Servicios', 'Servicios públicos (agua, luz, internet, etc.)', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Servicios');

INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Nómina', 'Pagos de salarios y prestaciones', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Nómina');

INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Renta', 'Pago de renta del local', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Renta');

INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Mantenimiento', 'Reparaciones y mantenimiento de equipos', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Mantenimiento');

INSERT INTO categorias_gasto (nombre, descripcion, activo, created_at)
SELECT 'Otros', 'Otros gastos varios', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM categorias_gasto WHERE nombre = 'Otros');

